services:
  frontend:
    image: patientor-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: patientor-front

  backend:
    image: patientor-backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: patientor-backend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend
      - backend